services:
  cache:
    image: redis
    ports:
      - '6379:6379'
    # --save 60 1 - saves data every 60 seconds if at least 1 new write has been made
    # --loglevel warning - reduces log amount to save space
    command: redis-server --save 60 1 --loglevel warning --requirepass '${REDIS_PASSWORD}'
    volumes:
      - cache:/data # /data is where --save persists data by default
volumes:
  cache:
    driver: local
